version: 0.1
log:
  level: info
  fields:
    service: registry

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: 'HEAD, GET, OPTIONS'
    Access-Control-Allow-Headers: 'Authorization'
