apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: exam
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/project"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"



