---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project
  namespace: exam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: exam-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-rolebinding
  namespace: exam
subjects:
  - kind: ServiceAccount
    name: project
    namespace: exam
roleRef:
  kind: Role
  name: exam-role
  apiGroup: rbac.authorization.k8s.io
